#!/usr/bin/env node
const argv = require('yargs')
    .alias('f', 'file')
        .nargs('f', 1)
        .describe('f','path to the file to be processed by the cli')
        .normalize('f')
    .alias('o', 'operation')
        .nargs('o', 1)
        .describe('o', 'the operation to perform with the submitted file')
        .choices('o', ['create', 'update', 'delete'])
    .alias('t', 'type')
        .nargs('t', 1)
        .describe('t', 'the type of file being submitted')
        .choices('t', ['api', 'policy'])
    .env('CLOUD_APIMGT')
        .alias('a','authorisation')
        .demandOption(['a'], 'Please provide the environment parameter CLOUD_APIMGT_AUTHORISATION to work with this tool')
    .usage("$0 --file ./path-to-file-relative-to-cwd --operation [create|update|delete] --type [api|policy]")
    .demandOption(['f', 'o', 't'], 'Please provide both file, operation and type arguments to work with this tool')
    .epilogue('the environment parameter CLOUD_APIMGT_AUTHORISATION needs to be set in order for this cli to function.')
    .help()
    .argv;
