pr:
  branches:
    include:
    - master
  paths:
    include:
    - apis/*
    exclude:
    - apis/non-production/*
    - apis/pre-production/*
    - apis/production/*

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: Build_and_Exec_Unit_Tests
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: 'Install Node.js'
          
          - script: |
              cd ./apis/
              npm install
            displayName: 'Install dependencies'
          
          - script: |
              cd ./apis/
              npm run test:showlogs
            displayName: 'run unit and integration tests'